server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  error_page 404 /404.html;

  location / {
    try_files $uri $uri.html $uri/ =404;
  }

  location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|avif|webp|mp4|pdf)$ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public";
  }
}
